version: '3.9'

services:
  service_users:
    build: ./service_users
    container_name: service_users
    ports:
      - "8001:8000"   # внешний порт 8001 → внутри контейнера 8000
    restart: unless-stopped

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"   # Gateway на 8000
    environment:
      - JWT_SECRET=supersecret
    depends_on:
      - service_users
    restart: unless-stopped
